# Generated by Django 5.1.3 on 2024-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.JSONField(default=list)),
                ('round2', models.JSONField(default=list)),
                ('final', models.JSONField(default=list)),
                ('campeao', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
