# Generated by Django 5.1.3 on 2024-11-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneio',
            old_name='final',
            new_name='rounds',
        ),
        migrations.RemoveField(
            model_name='torneio',
            name='round',
        ),
        migrations.RemoveField(
            model_name='torneio',
            name='round2',
        ),
        migrations.AddField(
            model_name='torneio',
            name='jogadores',
            field=models.JSONField(default=list),
        ),
    ]
